trainconfig:
  bs: 32
  lr: 0.0006
  max_epoch: 500

bertconfig:
  max_age: 120
  max_visit_rank: 2048
  max_record_rank: 2048
  max_domain: 5
  block_size: 2048
  n_layer: 6
  n_head: 12
  hidden_size: 768
  dropout: 0.3
  bias: True
  linear: True
  


  