batch_size: 1024
learning_rate: 0.0005
num_hidden: 768
num_proj_hidden: 768
activation: 'prelu'
base_model: 'GCNConv'
num_layers: 2
drop_edge_rate_1: 0.2
drop_edge_rate_2: 0.2
drop_feature_rate_1: 0.2
drop_feature_rate_2: 0.2
tau: 0.5
num_epochs: 200
weight_decay: 0.00001
seed: 100
patience: 20
num_neighbors: [30, 20, 10]