trainconfig:
  bs: 32
  lr: 0.00005
  max_epoch: 50

datasetconfig:
  masked_ratio: 0.3

bertconfig:
  max_age: 120
  max_visit_rank: 2048
  max_record_rank: 2048
  max_domain: 5
  hidden_size: 768
  num_hidden_layers: 6

  